---
############################
## roles/nas_db/tasks/db_13_deploy_program.yaml
## (ALL)
## 백업 복구 프로그램 배포
############################
- name: 백업 프로그램 스크립트 템플릿 배포
  ansible.builtin.template:
    src: backup_program.py.j2
    dest: /usr/local/bin/backup_program.py
    owner: "{{ nfs_owner_user }}"
    group: "{{ nfs_owner_user }}"
    mode: '0500'

